name: pages-build-site
# push到main时触发
on: 
  push:
    branches: 
      - main
jobs:
  deploy:
    # 最新版 Ubuntu
    runs-on: ubuntu-latest  	
    # name表示名称，uses表示使用的插件（见插件市场），with表示传给插件的参数
    steps:
      # 1. 拉取代码
      - name: Checkout 							
        uses: actions/checkout@v3
      
      # 2. 构建所需文件（使用pnpm） 
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build docs
        run: rm -r docs/.vitepress/dist && pnpm run docs:dev
        
      # 3. 把当前分支下的某个目录内容 部署到 GitHub Pages，
      # 方案1:JamesIves：https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy							
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # 项目secrets下的token 、部署的分支、移动的目录
          ACCESS_TOKEN: ${{ secrets.FORACTION }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist

